import ContactSection from "@/components/ContactSection";
import Hero from "@/components/Hero";
import HomeAbout from "@/components/HomeAbout";
import HomeIndustries from "@/components/HomeIndustries";
import HomeServices from "@/components/HomeServices";
import TestimonialsCarousel from "@/components/Testimonials";
import FeatureSection from "@/components/WhyChooseUs";

import { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Servmark - Ghana's number one expert solution to professional services",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      <Hero />
      <HomeAbout />
      <HomeIndustries />
      <HomeServices />
      <FeatureSection />
      <TestimonialsCarousel />
      <ContactSection />
    </div>
  );
}
